### ISSUE TITLE
Compass Won't Track.

### ISSUE THREAD

**Issue by JackSwanSong** [yummypasta/MinecraftManhunt#1] opened 2020-09-02 20:26 UTC
My friend and I tried to use this plugin on his server. When we started up the game the commands worked fine, but the compass wouldn't track me even when I was a speedrunner and after the headstart wore off.

**Comment by yummypasta** [comment] 2020-09-02 20:33
Hi @JackSwanSong , thanks for submitting an issue! Here's some potential fixes:

1) Did your friend right-click while holding the compass? After you type `/start`, you should be able to right-click to open the menu, then the hunter can click your head to start tracking you.
2) Make sure you assigned the appropriate roles with `/speedrunner` and`/hunter`. You will have to do this every time you restart the server.

Please let me know if that fixes the problem!

**Comment by JackSwanSong** [comment] 2020-09-03 00:00
Yes, we tried doing all of that. When my friend tries to do /start  it says "An internal error occurred while attempting to perform this command." but he goes blind still, but the compass still won't track.

**Comment by yummypasta** [comment] 2020-09-03 00:15
I believe the problem is actually a bug related to when Discord is disabled in `config`. I'm working on a fix right now.

**Comment by yummypasta** [comment] 2020-09-03 00:22
@JackSwanSong , A fix has been released:
[Version 1.1](https://github.com/yummypasta/MinecraftManhunt/releases/tag/v1.1)

Please download directly from the link above since the Bukkit website hasn't processed the new version yet.

Thanks for reporting this issue!

**Comment by yummypasta** [comment] 2020-09-05 08:21
Closing issue, as I'm assuming your issue had been resolved. Please reopen if this is not the case.

**Closed** 2020-09-05 08:21 UTC
Labels: bug
