### ISSUE TITLE
Discord Bot not playing music, and not working

### ISSUE THREAD

**Issue by FlaminMonkey** [yummypasta/MinecraftManhunt#3] opened 2020-09-11 01:27 UTC
Hey so I just want to start off by saying: This plugin is awesome. In my opinion, it is actually the best Manhunt Plugin for vanilla experience, and at the moment I'm still using it.
BUT-
After I set the bot up, with the token, discord channel/server ID's etc, I would run the /music auto command, and the Bot would leave and rejoin the Voice Channel, repeatedly over and over, and there is no way to stop it, doing /music stop doesn't work and I even tried variants of it (not that that would work). The only way I stopped it was stopping the server or kicking the bot from my discord. Also, In my Minecraft Server console, it sometimes says something along the lines of "failed to find song" or something on the startup. And- a few times, the compass would randomly not point to runners, but instead in the opposite direction. I have no idea what the cause could have been, but at some points the console was spammed with errors regarding the plugin, and I had to force stop my server because everyone timed out.
So for now, I have the plugin, but just have discord turned off until these issues are fixed, or I fix something I am doing wrong!

Anyway, thank you for making this amazing plugin, and I cannot wait until I can use it's full potential :D

**Comment by yummypasta** [comment] 2020-09-11 03:02
Hi @FlaminMonkey ,

Thanks for using the plugin and reporting this issue.

I'm aware of the "failed to find song" issue— One of the Youtube links containing the music was taken down. This will be fixed in the next release which I'll publish soon, but before that, I'd like to investigate these other issues a bit.

Can you please upload your Server console logs that contain the errors? I've never seen the bot leave and join the channels, so your logs would be very helpful.

Finally, could you please provide a copy of your `config.yml`? Feel free to take out your Discord bot token for privacy purposes.

**Comment by yummypasta** [comment] 2020-09-11 03:05
And one more thing I forgot to mention: does the bug, by any chance, only happen when you're in the nether? I'm aware with warnings being printed to the console when the runners/hunters are in different dimensions, and I'm wondering if that might be the cause.

**Comment by FlaminMonkey** [comment] 2020-09-11 04:04
![image](https://user-images.githubusercontent.com/71108828/92854046-6356ae80-f3a5-11ea-9da1-9106a961e74b.png)
(idk if that upload worked, so i'll also paste what it says here)
also I know discord is disabled, but it was enabled when the discord bugs happened!

headStartDuration: 15
compassEnabledInNether: true

enableDiscord: false
discordToken: "XXXXX"
ip: "a minecraft server"

discordServerId: "741863982532395049"
musicChannelId: "753488144351100969"
hunterRoleId: "753664845576142958"
runnerRoleId: "753664932712677418"
spectatorRoleId: "753665225529622738"

The crash errors are too far up in the console, since I've hosted Manhunts since, sorry :/

I have a plugin called GeyserMC, that allows Bedrock players to play on my server, and I don't think this has anything to do with it but a few of the players's compasses would randomly lead them in a different direction. It could be just the players being far away, I'm not 100% sure just thought I would let you know :D 
If I see the errors again I will come back here

**Comment by yummypasta** [comment] 2020-09-11 04:07
Your config seems OK. I couldn't reproduce the issue, but if you do see the console logs, please do post them.

I have not tested this plugin with GeyserMC— it could very well be a compatibility issue.

If the compasses go in the wrong direction, try having the players re-select the targets; that might fix it!

**Comment by FlaminMonkey** [comment] 2020-09-11 04:10
Alright will do! Also everything seems to work besides that, like the GUI and everything and other plugins that don't necessarily support Geyser all work so I don't believe that is the issue!

**Comment by yummypasta** [comment] 2020-10-31 04:11
Hi @FlaminMonkey,

If you are still trying to get the Manhunt plugin set up, try upgrading to the latest version (currently [1.2.4](https://github.com/yummypasta/MinecraftManhunt/releases/tag/v1.2.4)). Also, make sure the computer running your server's date clock is set right, as described in #9.

**Comment by yummypasta** [comment] 2020-11-09 21:14
Closed as old, please reopen if you have any more problems.

**Closed by yummypasta** 2020-11-09 21:14 UTC
Labels: bug
