### ISSUE TITLE
Dead link?

### ISSUE THREAD

**Issue by TXCZodiac** [yummypasta/MinecraftManhunt#2] opened 2020-09-07 23:02 UTC
Trying to link the discord app but the link is taking me to an error window. Possibly dead?

**Comment by yummypasta** [comment] 2020-09-08 02:00
Hi @TXCZodiac ,

If the window is showing a big "X", that means your client id is wrong.

Please make sure your URL is in the form:
```
https://discord.com/oauth2/authorize?scope=bot&client_id=123YourClientID456&permissions=8
```
Then, go to your [Discord Developer Portal](https://discord.com/developers/applications) and replace `123YourClientID456` with the Client ID you find, like below:
<img width="1569" alt="Screen Shot 2020-09-07 at 6 42 27 PM" src="https://user-images.githubusercontent.com/12377772/92424831-3fdbfb80-f13a-11ea-96ca-118518705a93.png">

Please close the issue if this works! Otherwise, leave a reply.

**Comment by yummypasta** [comment] 2020-09-10 06:59
Assuming the issue is resolved, closing. If this is not the case, please reopen.

**Closed by yummypasta** 2020-09-10 06:59 UTC
