### ISSUE TITLE
Compass doesn't work on 1.16.1 only on 1.16.4

### ISSUE THREAD

**Issue by PancakeMomche** [yummypasta/MinecraftManhunt#34] opened 2020-11-30 22:30 UTC
## Describe the bug
On 1.16.1 the compass points to world spawn for every hunter except the host. On 1.16.4 everything works perfectly.

## Environment Info
**Plugin version:** 1.3.3.2
**Bukkit/Spigot server version:** 1.16.1
## Configuration file
```
headStartDuration: 30
compassEnabledInNether: true
sendUsageData: true
enableDiscord: false
discordToken: XXXXX
ip: a minecraft server
processDiscordCommands: true
discordServerId: XXXXX
musicChannelId: XXXXX
hunterRoleId: XXXXX
runnerRoleId: XXXXX
spectatorRoleId: XXXXX
uuid: b4ce66fc-3d1d-4cd9-82c5-3c25f7f379fe
```

## Server Logs
```
Nothing particular but i'll have to check again next time i play
```

## Anything else?
Doesn't matter if online-mode is true or false. Compass doesn't work in both cases.

**Comment by yummypasta** [comment] 2020-12-01 01:08
Hi @PancakeMomche,
Thanks for using the plugin. I'll look into this issue and get back to you if I find the problem/a solution.

**Comment by yummypasta** [comment] 2020-12-01 02:59
I just tested the plugin in 1.16.1 and I cannot reproduce this issue, even with two players. Please post your entire server logs next time this error happens and I may be able to find the problem!

**Comment by PancakeMomche** [comment] 2020-12-01 09:44
Here are the logs for the 1.16.1 test we did:
[log.txt](https://github.com/yummypasta/MinecraftManhunt/files/5621629/log.txt)

Also i noticed in 1.16.1 the compasses are not enchanted an only work for one person

**Comment by yummypasta** [comment] 2020-12-01 16:44
Thanks for the logs, I found that is wrong. According to the logs you are running CraftBukkit at commit `7560f5f` but CompassMeta (a feature necessary for the plugin) was added at commit [`b8b65eb744c`](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/b8b65eb744c410438b8c1b3b4351e605ee909366)
This is also warned by the logs by the error at the top:
```
*** Error, this build is outdated ***
*** Please download a new build as per instructions from https://www.spigotmc.org/go/outdated-spigot ***
*** Server will start in 20 seconds ***
```

**Solution:** Please update your spigot version to the latest 1.16.1 build by running BuildTools again.
```bash
java -jar BuildTools.jar --rev 1.16.1
```

Feel free to close this issue if this works! If the fix does not work I'll keep looking.

**Comment by PancakeMomche** [comment] 2020-12-01 18:01
Now a new issue occured. Compasses say "target is null
Here is the new log
"
[log 2.txt](https://github.com/yummypasta/MinecraftManhunt/files/5624488/log.2.txt)
"

**Comment by yummypasta** [comment] 2020-12-01 18:16
Thanks for the new logs. I'll look into the errors but I have a hunch that this is caused by online-mode being false.

**Comment by PancakeMomche** [comment] 2020-12-01 18:52
Tested 1.16.1 with online-mode being true and it works. Sounds it's most likely that, but is there a fix?

**Comment by yummypasta** [comment] 2020-12-01 19:00
Unfortunately I haven't found a way to make the plugin work in offline mode yet, but I'm working on it. Follow issue #13 for updates on when I fix it!

(I'm going to close this issue, feel free to reopen or submit a new one if you have any more issues)

**Closed by yummypasta** 2020-12-01 19:00 UTC
Labels: bug

**Comment by yummypasta** [comment] 2020-12-02 21:54
Support for offline mode has been added in [version 1.3.3.4](https://github.com/yummypasta/MinecraftManhunt/releases/tag/v1.3.3.4)!
